### ISSUE TITLE
Rework gamification interaction

### ISSUE THREAD

**Issue by jaycrossler** [ngageoint/geoq#237]
Refactor the gamification interaction to make it more modular and to eventually work with other applications.

- [x] Move all gamification code to gamification.js and major object
- [x] Order by Badge count
- [x] Move to use settings object, not settings.py
- [x] Have multiple projects
- [x] Show points
- [ ] Show Leaderboard
- [ ] Save badge json to user model
- [x] Show badge counts over badge icons

**Comment by stephenrjones** [comment]
Code has been moved to gamification-server project
