### ISSUE TITLE
Mapillary integration with GeoQ

### ISSUE THREAD

**Issue by Whatsupcory** [ngageoint/geoq#258]
Mapillary is simply a native ios/android app that lets people make their own street view like imagery just by driving, riding a bike or walking.  GeoQ could possibly crowd source post imagery by asking locals to use Mapillary. 
See video below (caution music)

http://vimeo.com/91600402

Can we make it easy for GeoQ analysts to have Mapillary imagery in GeoQ?

API documentation: http://www.mapillary.com/developer.html

**Comment by Whatsupcory** [comment]
@jaycrossler Are you back on GeoQ development?

**Comment by jaycrossler** [comment]
I am! Excited to finally be doing real work again.

**Comment by jackiekazil** [comment]
YAY! :sparkles: :us: :sparkles:

**Comment by peterneubauer** [comment]
Very cool, exciting to see your progress!
