### ISSUE TITLE
AOI GeoJSON not displaying grid colors

### ISSUE THREAD

**Issue by chrisjgithub** [ngageoint/geoq#261]
Exported a "Share Your Work" AOI(geoJson) workcell grid (mouse over says "polygons and data of all job workcells". Then created a layer in GeoQ called Area of Interest BfS  (URL http://geo-q.com/geoq/api/job/10/grid/job-workcells.geojson)  -- No data is visible, only workcell grid is shown (which is ok since I only wanted the grids). However, no cell grid colors (g,r,y) displaying. 

![image](https://cloud.githubusercontent.com/assets/6785683/4548447/3316d412-4e55-11e4-8863-97e3daba0a16.png)

When turning the layer on/off, the layer is duplicated and grids become solid red.  Refresh map layer and feature number duplicates

![image](https://cloud.githubusercontent.com/assets/6785683/4548479/623cf668-4e55-11e4-8254-0ff81625dd82.png)

**Comment by stephenrjones** [comment]
This should now be fixed. Was a real nuisance -- at the moment we applied the layer attributes, not all of them had been loaded (true for GeoJSON's or anything extended from that class, such as Shapefiles). Now using layer loaded trigger to apply the attributes
