### ISSUE TITLE
Document impact of geoq w/ a blog update?

### ISSUE THREAD

**Issue by jackiekazil** [ngageoint/geoq#297]
Hello! Has the impact of this project has been documented anywhere -- such as a blog post?

**Comment by stephenrjones** [comment]
Hi Jackie,
We've started assembling our wiki to capture some of this information. Chris Johnson has added quite a bit regarding GEO-Huntsville's use:

https://github.com/ngageoint/geoq/wiki/Geo-Huntsville

Steve

**Comment by jackiekazil** [comment]
Thank you for pointing me to that!

**Comment by Bauerr** [comment]
Hi jackie,  You may also want to look at the press/media section of the GeoQ help page ( http://www.geo-q.com/geoq/help

**Comment by jackiekazil** [comment]
Thank you!
