### ISSUE TITLE
User Diplay does not fill screen

### ISSUE THREAD

**Issue by Bauerr** [ngageoint/geoq#298]
After creating several projects in the past few weeks it seems that introducing any level of complexity into the work cell creation or possibly higher or lower latitude cell creation prevents the user screen for maximizing the GeoQ analysis window. 
![rio](https://cloud.githubusercontent.com/assets/7875881/7031144/64769ada-dd37-11e4-9b60-61bc0532613e.jpg)

**Comment by stephenrjones** [comment]
Found that this behavior is due to an error creating a WMTS layer. Need to add some error catching as well as handling that layer

**Comment by stephenrjones** [comment]
Some error checking as been added to WMTS layers, so will continue to monitor and re-open if issue reoccurs.
