### ISSUE TITLE
Map Items -> Map 

### ISSUE THREAD

**Issue by Prindle19** [ngageoint/geoq#299]
when logged in as super admin, I don't see "Map" as an option under Map Items. 

I see:

Layers
Feature Types. 

I can only edit maps via the django admin site. 

I can see the Maps section in the ui if I manually go to /maps/maps

**Comment by stephenrjones** [comment]
That's a change we made to (hopefully) make things a little easier. When a Job is created now, a new map is automatically created and associated with that Job. That way Jobs won't be sharing a map, which at times caused confusion as configuring a map for one Job may effect another. You should still be able to get to the map configuration page by going to the Job details page and under the menu dropdown to the right select 'Edit Map'

**Comment by Prindle19** [comment]
Ok - makes sense and can confirm that workflow - help videos a bit out of date :)
