### ISSUE TITLE
Create navigation map

### ISSUE THREAD

**Issue by stephenrjones** [ngageoint/geoq#301]
From R3 folks: when zoomed in close on a workcell, they'd like an overview map that gives an indication where they are currently looking within the workcell.

**Comment by Prindle19** [comment]
+1 - agree that would be usefull

**Comment by stephenrjones** [comment]
This has been implemented in the newest update. When in the workcell view, the tools section now has a 'Geo Overview' tab. We will eventually need to remove the hard-coded layer path in here.
