### ISSUE TITLE
Display Map Base Layers in Project / Job Overview Maps

### ISSUE THREAD

**Issue by Prindle19** [ngageoint/geoq#303]
I found it very confusing why layers I was adding to a map were not showing up until I created work cells. 

I actually thought that they weren't working. 

Feature Request to make Custom map layers visible on the overview maps; either by default (as they are when you open a work cell) or by option in map configuration.

**Comment by stephenrjones** [comment]
Hi Sean,

Would it be helpful to list the layers on the Job page just as a confirmation of what's on the map? I'm a little leery of adding too much to that map as I don't want that page to get dragged down too much. I know we have discussed making some layers available in other views, most notably the workcell creation, as there definitely could be some information that would assist for that particular task.

**Comment by Prindle19** [comment]
My use case is I'm trying to use GeoQ for an imagery QA / QC platform. 

The imagery being QA/QC'd is a single Z/X/Y Tile Layer, so, I'm not trying to lay too much on top of the map, but I see where that could get lagged down if people had a bunch of layers turned on. 

But, it would be helpful to see the imagery layer front and center when you get to the Job page.

Not sure a list of layers would be helpful without actually being able to see them.

Maybe some soft limit for permitted layers turned on in the Job page.(that admins could adjust if they don't mind the risk of having too many layers turned on)?

**Comment by stephenrjones** [comment]
The Job page is really designed to be more informational. I could definitely see where having a tile layer available when creating workcells would be very beneficial -- you could display the tile imagery, create your workcells dependent on that, then assign or work on the cells starting from the Job page. Would that fit your use case?

**Comment by Prindle19** [comment]
Yes, That would also be useful.

However, if you were able to change the basemap from always being OSM, this
would be alleviated because the jobs page map would show whatever basemap I
had set.


On Fri, Apr 10, 2015 at 7:43 AM, Stephen Jones <notifications@github.com>
wrote:

> The Job page is really designed to be more informational. I could
> definitely see where having a tile layer available when creating workcells
> would be very beneficial -- you could display the tile imagery, create your
> workcells dependent on that, then assign or work on the cells starting from
> the Job page. Would that fit your use case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ngageoint/geoq/issues/303#issuecomment-91528823>.
>



-- 
Sean Wohltman - WG0OGL | Geospatial Scientist | seanwohltman@google.com |
703-677-8626

**Comment by stephenrjones** [comment]
We've added the capability to overlay WMS, KML, and shapefiles onto the Job detail map and Assign workcells map. In order to implement this functionality, add a layer to the job, then in the edit map page set the switch to 'display in layer switcher'. Would be relatively straightforward to add other layer types in a similar manner -- see leaflet_helper.addLayerControl in leaflet_helper.js
