### ISSUE TITLE
KML/KMZ as Overlays in Create Workcell page

### ISSUE THREAD

**Issue by chrisjgithub** [ngageoint/geoq#309]
Bring in KML/KMZ as an overlay layer in Create workcell page. Users would use overlay as a reference when drawing new workcell areas.

**Comment by stephenrjones** [comment]
This has been added in the latest upgrade. Only additional step required beyond adding KML/KMZ file to a Job is that in the 'Map' view check the 'Display in Layer switcher' checkbox
