### ISSUE TITLE
Allow posting of features to OpenStreetMaps

### ISSUE THREAD

**Issue by jaycrossler** [ngageoint/geoq#312]
Have certain features to post to OpenStreetMaps.  Have the ability to specify user account information in settings (maybe by user setting?) that then passes edits as changesets back to the osm API.

Details on the API Changesets are here:
http://wiki.openstreetmap.org/wiki/API_v0.6 

There is probably some warnings/training/other concepts that should be shown to the user, and maybe some additional metadata that needs to be added to the post requests.

**Comment by stephenrjones** [comment]
Part of this functionality has been added to the system
