### ISSUE TITLE
Points In Google Earth Not working

### ISSUE THREAD

**Issue by Bauerr** [ngageoint/geoq#320]
In support of the Van Tx tornado support (Job 53 on App03) the points are not appearing in Google Earth. The assignment grid is appearing.

**Comment by stephenrjones** [comment]
Appears that lines 175-185 in geoq/core/kml_view.py had excessive indentation. Moving those lines in 8 spaces should resolve the problem. Don't believe this should effect any other servers.

**Comment by stephenrjones** [comment]
Appears that points are now appearing in Google Earth
