### ISSUE TITLE
Link to GeoQ logo

### ISSUE THREAD

**Issue by Bauerr** [ngageoint/geoq#322]
I was referencing the logo to show on the Talking Points section of the GeoQ wiki here: https://geo-q.com/geoq-static/images/GeoQ-Logo.png and for some reason that I can not figure out it has stopped displaying on the page.  So I am putting the image in this issue ticket to try and use this as a temporary home and then I will use the link in the wiki to see if it works. Can we upload the image to the https://raw.githubusercontent.com/wiki/ngageoint/geoq/images/ site so i can permanently use that link instead?

![geoq-logo](https://cloud.githubusercontent.com/assets/7875881/7788848/a9465ab8-0219-11e5-8802-ad5bfff7e802.png)

**Comment by Bauerr** [comment]
It worked!

**Comment by stephenrjones** [comment]
So you should be able to get it at: https://raw.githubusercontent.com/wiki/ngageoint/geoq/images/GeoQ-Logo.png

**Comment by Bauerr** [comment]
Thanks. 

Ray
