### ISSUE TITLE
Layer attributes

### ISSUE THREAD

**Issue by stephenrjones** [ngageoint/geoq#324]
Several layers that we currently use (digital globe, CAP imagery) can take different attributes to tailor the output to better define what is displayed on the map. Some of these attributes can include a date range or an eventID. Currently, to handle this situation we have to create a new layer for each attribute that we're looking to modify. Suggest we create a means for users to interactively modify appropriate attributes for a layer, eliminating this need for multiple layers.

**Comment by Bauerr** [comment]
Thanks for entering this and making it high priority. 

Ray

**Comment by stephenrjones** [comment]
This has been addressed, and currently supports string, date, and integer variables in a url
