### ISSUE TITLE
Fail to display GEOJSON Points as Data Feed

### ISSUE THREAD

**Issue by ubriela** [ngageoint/geoq#337]
I try to add a FeatureCollection of Point (sample below); however, the data points are not counted and shown on map (see screenshot).
https://raw.githubusercontent.com/ubriela/test/master/mediaq3.geojson
![screenshot 2015-07-16 13 14 28](https://cloud.githubusercontent.com/assets/3415436/8734138/cf8f023e-2bbc-11e5-8f95-f8fa8c338e99.png)
I try to inspect and figure out that the function call outputLayer.addData(geojson) on leaflet_parser_helpers.js did not successfully add the geojsond data. This is because an exception in leaflet-sc.js, the layer parameter is undefined for some reason.
var layer = L.GeoJSON.geometryToLayer(geojson, options.pointToLayer, options.coordsToLatLng, options);
layer.feature = L.GeoJSON.asFeature(geojson);

**Comment by stephenrjones** [comment]
I've pulled Khazhy's fix into my system and I'm seeing the points on the map. We'll continue to expand the capabilities using the services you defined to see if we can successfully query your system.
