### ISSUE TITLE
Code Update reference in log in window

### ISSUE THREAD

**Issue by Bauerr** [ngageoint/geoq#345]
Previously when we updated the code baseline on a system the date of the update was viewable in the login pull down tab.  Can we get that feature back?

**Comment by stephenrjones** [comment]
That functionality is enabled by having a '.git' file or directory exist in the top-level directory. We'll do a 'touch .git' in that directory and the date will be restored

**Comment by stephenrjones** [comment]
Doing the 'touch .git' does resolve the problem, but we'll need to look for a way to update this automatically. Will close this  issue and possibly open a new one to resolve that
