### ISSUE TITLE
Migration error with database after >> paver sync

### ISSUE THREAD

**Issue by ubriela** [ngageoint/geoq#349]
Exception after >> sudo paver sync
-----------------
Running migrations for core:
 - Migrating forwards to 0019_auto__add_field_job_editable_layer.
 > core:0019_auto__add_field_job_editable_layer
FATAL ERROR - The following SQL query failed: ALTER TABLE "core_job" ADD CONSTRAINT "editable_layer_id_refs_id_e57d021f" FOREIGN KEY ("editable_layer_id") REFERENCES "maps_editablemaplayer" ("id") DEFERRABLE INITIALLY DEFERRED;
The error was: relation "maps_editablemaplayer" does not exist

Error in migration: core:0019_auto__add_field_job_editable_layer
DatabaseError: relation "maps_editablemaplayer" does not exist

**Comment by nstarke** [comment]
I am seeing this issue as well.

**Comment by nstarke** [comment]
Work around to get past this error is to run ```python manage.py migrate geoq.maps```, though that leads to another error.  Try to run ```paver sync``` on the ```develop``` branch, that worked for me.

**Comment by stephenrjones** [comment]
A fix for this issue should be in the develop baseline now
