### ISSUE TITLE
National Symbology for Public Alerts and Warnings with NWS CAP/XML and ATOM Formats

### ISSUE THREAD

**Issue by chrisjgithub** [ngageoint/geoq#361]
Integrate National Symbology set for Public Alerts and Warnings to display NWS watches, warnings, advisories, and other similar products in the Common Alerting Protocol (CAP) and Atom Syndication Format (ATOM)

**Comment by stephenrjones** [comment]
Initial integration of the symbols has been completed. Needs a bit of documentation
