### ISSUE TITLE
MAGE icons missing 

### ISSUE THREAD

**Issue by dcwalrath** [ngageoint/geoq#364]
I created a new MAGE layer and added it to an existing project.  Some of the event type icons (i.e. VIP) associated with my observations are visible on the map, but others, like "other activity" or "other event", are missing.

**Comment by stephenrjones** [comment]
Thanks Dave. I realized that I wasn't matching up on icon urls with spaces in them -- have pushed the fix, so hopefully it should be good now.

**Comment by dcwalrath** [comment]
Thanks, Steve!  I'll pull the updates and let you know if I have any issues.

Have a great day!

David
