### ISSUE TITLE
Determine base map at time of map creation

### ISSUE THREAD

**Issue by jaalfaro** [ngageoint/geoq#74]
Related to #43.

Right now it appears there is a system base map that all maps get.  The base map for a map should be map specific and not some system default.  The easiest solution would be to add an additional field to the layers that indicates if a layer is a base map and provide the user a list of the base maps similar to what is done to add layers to a base map.  You could still add additional base maps to the map, but the default base map would that that specified vs that of the system default.

**Comment by stephenrjones** [comment]
Closing issue. OSM basemap can now be overridden by the user after creating Job
